---
- hosts: webservers
  become: yes
  tasks:
  - name: display host name
    command: hostname -f
    register: myresult

  - name: display first task result
    debug:
      msg: "{{myresult}}"

  - name: installgit 
    apt:
      name: git
    when: myresult.stderr ==""
  
  - name: install tree
    apt:
      name: tree
    when: myresult.stderr !=""