
---
- hosts: webservers
  become: yes
  tasks:
  - name: install webservers 
    apt: 
      name: apache2
      state: present
  - name: start webservers
    service:
      name: apache2
      state: started

  - name: copy index.j2 into all nodes
    template:
      src: index.j2
      dest: /var/www/html/index.html
    
  
