---
- hosts: all
  become:  yes
  tasks:
  - name: install webserver on ubuntu16
    apt:
      name: apache2
      state: present
  - name: start webserver on ubuntu16
    service:
      name: apache2
      state: started